# Generated by Django 6.0.5 on 2026-05-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100)),
                ("stock", models.CharField(blank=True, max_length=100)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[("35mm", "35mm"), ("120", "120"), ("other", "Other")],
                        max_length=10,
                    ),
                ),
                ("iso", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("camera", models.CharField(blank=True, max_length=100)),
                ("loaded_at", models.DateField(blank=True, null=True)),
                ("max_frames", models.PositiveSmallIntegerField(default=36)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("loaded", "Loaded"),
                            ("exposed", "Exposed"),
                            ("at_lab", "At lab"),
                            ("scanned", "Scanned"),
                        ],
                        default="loaded",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rolls",
                        to="studio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
