# Generated by Django 6.0.5 on 2026-05-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_filmroll"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_number", models.PositiveSmallIntegerField()),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="studio.filmroll",
                    ),
                ),
            ],
            options={
                "ordering": ["frame_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roll", "frame_number"), name="unique_frame_per_roll"
                    )
                ],
            },
        ),
    ]
