# Generated by Django 6.0.5 on 2026-05-21

from django.db import migrations, models


def copy_fk_to_m2m(apps, schema_editor):
    """Keep existing roll → project links when switching to many-to-many."""
    FilmRoll = apps.get_model("studio", "FilmRoll")
    for roll in FilmRoll.objects.exclude(project_id=None):
        roll.projects.add(roll.project_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_framenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmroll",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="rolls",
                to="studio.project",
            ),
        ),
        migrations.RunPython(copy_fk_to_m2m, noop_reverse),
        migrations.RemoveField(
            model_name="filmroll",
            name="project",
        ),
    ]
