# Generated by Django 6.0.5 on 2026-05-27 16:17

import studio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_roll_projects_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="framenote",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=studio.models.frame_image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="framenote",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
