# Generated by Django 6.0.5 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_framenote_image_alter_framenote_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="framenote",
            name="frame_number",
            field=models.SmallIntegerField(),
        ),
    ]
