# Generated by Django 6.0.5 on 2026-05-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_alter_framenote_frame_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="framenote",
            name="scan_filename",
            field=models.CharField(
                blank=True,
                help_text="Original lab scan filename, if imported.",
                max_length=255,
            ),
        ),
    ]
