# Generated by Django 6.0.5 on 2026-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0007_framenote_scan_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="framenote",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
